### PR TITLE
Runs with missing results will fail and runs that fail to start after building will send notifications

### LINKED ISSUE #146: Runs can succeed when they fail to get results
If a template_result mapping is incorrect, and carrot fails to get the result from the run, it does not mark the run as failed, which can mean the user cannot fix the issue because the run can succeed.  This should be changed so failing to get a mapping result is recognized as a run failure.

### PR DESCRIPTION
**Pull request by KevinCLydon**
Fixes two bugs:

1. Runs would not be marked as failed when there were results missing from what was expected, based on the results mapped to the run's template. (Fixes #146 )
2. Runs that failed in some part of the test-starting process after completing a build would not send notifications of the run's failure.

### CODE REVIEW

File: src/routes/pipeline.rs [hunk 1]
```diff
@@ -5,7 +5,7 @@
 
 use crate::db;
 use crate::models::pipeline::{NewPipeline, PipelineChangeset, PipelineData, PipelineQuery};
-use crate::routes::error_handling::{ ErrorBody, default_500 };
+use crate::routes::error_handling::{default_500, ErrorBody};
```
Comment (jonn-smith) [inline src/routes/pipeline.rs:8]: I notice that often in these PRs there is some reformatting that happens.  It's not an issue - I'm just wondering if you know why it might be happening.  It's usually something like this reordering, or whitespace changes.

**Review by jonn-smith — APPROVED** [review]
Looks good to me!

I had a quick meta question, but the code looks fine.  Feel free to merge.

File: src/routes/pipeline.rs (hunk 1 above)
Comment (KevinCLydon) [reply src/routes/pipeline.rs:8]: I run `cargo fmt` to do code formatting, and I usually try to do it before every commit, but sometimes I forget, so I think stuff like this probably results from me committing without formatting and then remembering to format on a subsequent commit.

Comment (jonn-smith) [reply src/routes/pipeline.rs:8]: OK, cool.  That's what I figured.  It might be worth trying to automate this in the future (VERY low priority).
